#!/bin/bash
######################################################################
# Copyright (c) 2022, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

FROM pcmt/cron:3.0.0-snapshot

RUN apk -v --update add openssh && \
    rm /var/cache/apk/*