######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
    ansible.inventory_path = "inventory.ini"
    ansible.version = "2.10.8" 

  end

end