######################################################################
# Copyright (c) 2023, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  # see https://yarnpkg.com/lang/en/docs/cli/cache/
  HOST_YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/yarn"
  # see https://on.cypress.io/caching
  HOST_CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  HOST_COMPOSER_HOME: "$CI_PROJECT_DIR/.cache/composer"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/yarn
    - cache/Cypress

default:
  image:
    name: docker/compose:1.29.2
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - apk add bash make git curl libxml2-utils bc
    - bash --version
  ############### PCMT VERSIONS (for deploy) ###############


.pcmt_v_3_0_0:
  variables:
    PCMT_VER: '3.0.0-snapshot'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt-akeneov6/-/archive/master/pcmt-akeneov6-master.tar.gz'

############### PIM ###############

.pim_only_changes:
  only:
    changes:
      - '.gitlab-ci.yml'
      - 'src/**/*'
      - '.pcmt.env'
      - 'config/**/*'
      - 'conf/**/*'
      - 'scripts/**/*'
      - 'upgrades/**/*'
      - 'docker-compose.yml'
      - 'docker-compose.tls.yml'
      - 'docker-compose.prod.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
      - 'composer.json'
      - 'composer.lock'
      
.pim_docker_build:
  stage: build
  script:
    - scripts/ci-test.sh
    - scripts/ci-parse-coverage.sh $CODE_COVERAGE_THRESHOLD
    - scripts/ci-build.sh
    - scripts/ci-push.sh
  artifacts:
    paths:
      - build/unit-results.xml
    expire_in: 1 week

pim_docker_build_on_push:
  extends:
    - .pim_docker_build
    - .pim_only_changes

pim_docker_build_manual:
  extends: .pim_docker_build
  when: manual

############### IoC ###############

ansible docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/ansible/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make ansible
    - docker push pcmt/ansible:forv6

terraform docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/terraform/Dockerfile
      - deploy/terraform/run-docker.sh
      - deploy/terraform/script/**/*
      - deploy/terraform/env/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make terraform
    - docker push pcmt/terraform:v6

cron docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/cron/**/*
  except:
    changes:
      - deploy/mysql-backup/**/*
  script:
    - make cron
    - docker push pcmt/cron:3.0.0-snapshot

mysql-backup docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/mysql-backup/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make mysql-backup
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/mysql-backup:3.0.0-snapshot

asset-backup docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/asset-backup/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make asset-backup
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/asset-backup:3.0.0-snapshot

s3 docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/s3/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make s3
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/s3:3.0.0-snapshot
az-storage docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/azure-storage/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make az-storage
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/az-storage:3.0.0-snapshot
ftp-get docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/ftp-get/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make ftp-get
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/ftp-get:3.0.0-snapshot

ftp-put docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/ftp-put/**/*
      - deploy/cron/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make ftp-put
    - docker push pcmt/cron:3.0.0-snapshot
    - docker push pcmt/ftp-put:3.0.0-snapshot

scp-put docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/scp-put/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make scp-put
    - docker push pcmt/scp-put:3.0.0-snapshot

############### smart-test.productcatalog.io Environment ################

.env-smart-test:
  extends:
    - .pcmt_v_3_0_0
  stage: deploy
  only:
    - master@pcmt/pcmt-akeneov6
  variables:
    PCMT_PROFILE: dev
  except:
    variables:
      - $CI_SELENIUM == "true"
  environment:
    name: smart-test
    url: http://smart-test.productcatalog.io
    on_stop: env-smart-test-destroy

.env-smart-test_script-deploy:
  script:
    - source .ci-smart-test.env
    - ./scripts/ci-deploy.sh smart-test

.env-smart-test_script-destroy:
  script:
    - ./deploy/terraform/run-docker.sh smart-test destroy -auto-approve

env-smart-test:
  extends:
    - .env-smart-test
    - .env-smart-test_script-deploy

env-smart-test-destroy:
  extends:
    - .env-smart-test
    - .env-smart-test_script-destroy
  when: manual
  environment:
    name: smart-test
    action: stop

############### test-ansible.productcatalog.io Environment ###############

.env-test-ansible-pc-io:
  extends:
    - .pcmt_v_3_0_0
  stage: deploy
  only:
    - master@pcmt/pcmt-akeneov6
  when: manual
  needs: []
  variables:
    PCMT_PROFILE: prod
  except:
    variables:
      - $CI_SELENIUM == "true"
  environment:
    name: test-ansible-pc-io
    url: http://test-ansible.productcatalog.io
    on_stop: env-test-ansible-pc-io-destroy

.env-test-ansible-pc-io_script-deploy:
  script:
    - source .ci-productcatalog-io.env
    - ./scripts/ci-deploy.sh test-ansible-pc-io

.env-test-ansible-pc-io_script-destroy:
  script:
    - ./deploy/terraform/run-docker.sh test-ansible-pc-io destroy -auto-approve

env-test-ansible-pc-io:
  extends:
    - .env-test-ansible-pc-io
    - .env-test-ansible-pc-io_script-deploy

env-test-ansible-pc-io-destroy:
  extends:
    - .env-test-ansible-pc-io
    - .env-test-ansible-pc-io_script-destroy
  when: manual
  environment:
    name: test-ansible-pc-io
    action: stop
