######################################################################
# Copyright (c) 2023, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  # see https://yarnpkg.com/lang/en/docs/cli/cache/
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/yarn"
  # see https://on.cypress.io/caching
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/yarn
    - cache/Cypress

default:
  image:
    name: docker/compose:1.29.2
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - apk add bash make git curl libxml2-utils bc
    - bash --version
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  cache:
    paths:
      - .composer-cache/
  ############### PCMT VERSIONS (for deploy) ###############


.pcmt_v_3_0_0:
  variables:
    PCMT_VER: '3.0.0'
    PCMT_ASSET_URL: 'https://gitlab.com/pcmt/pcmt-akeneov6/-/archive/master/pcmt-akeneov6-master.tar.gz'

############### PIM ###############

.pim_only_changes:
  only:
    changes:
      - '.gitlab-ci.yml'
      - 'src/**/*'
      - '.env'
      - '.pcmt.env'
      - 'config/**/*'
      - 'conf/**/*'
      - 'scripts/**/*'
      - 'upgrades/**/*'
      - 'docker-compose.yml'
      - 'docker-compose.tls.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
.pim_docker_build:
  stage: build
  script:
    - scripts/ci-build.sh
    - scripts/ci-push.sh

pim docker build (on git push):
  extends:
    - .pim_docker_build
    - .pim_only_changes

pim docker build (manual retry):
  extends: .pim_docker_build
  when: manual

############### IoC ###############

ansible docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/ansible/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make ansible
    - docker push pcmt/ansible:latest

terraform docker build:
  stage: build
  only:
    refs:
      - master@pcmt/pcmt-akeneov6
    changes:
      - deploy/terraform/**/*
  except:
    variables:
      - $CI_SELENIUM == "true"
  script:
    - make terraform
    - docker push pcmt/terraform:latest

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:   # This job also runs in the test stage.
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

############### Test.productcatalog.io Environment ###############

.env-test-pc-io:
  extends:
    - .pcmt_v_3_0_0
  stage: deploy
  needs: []
  variables:
    PCMT_PROFILE: dev
  environment:
    name: test-pc-io
    url: http://test.productcatalog.io
    on_stop: env-test-pc-io-destroy

.env-test-pc-io_script-deploy:
  script:
    - ./scripts/ci-deploy.sh test-pc-io

.env-test-pc-io_script-destroy:
  script:
    - ./deploy/terraform/run-docker.sh test-pc-io destroy -auto-approve

env-test-pc-io:
  extends:
    - .env-test-pc-io
    - .env-test-pc-io_script-deploy

env-test-pc-io-destroy:
  extends:
    - .env-test-pc-io
    - .env-test-pc-io_script-destroy
  when: manual
  environment:
    name: test-pc-io
    action: stop
