######################################################################
# Copyright (c) 2023, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: '3.7'
services:

  httpd:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpd.rule=Host(`${PCMT_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.httpd.entrypoints=websecure"
      - "traefik.http.routers.httpd.tls.certresolver=myresolver"
      - "traefik.http.middlewares.httpd.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpd.redirectscheme.permanent=true"
      - "traefik.http.middlewares.httpd.redirectscheme.port=443"
  reverse-proxy:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pcmt2@villagereach.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${DOCKER_PORT_HTTPS:-443}:443"
      - "8080:8080"
    volumes:
      - type: volume
        source: traefikdata
        target: "/letsencrypt"
  
volumes:
  traefikdata:
    driver: local