######################################################################
# Copyright (c) 2023, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.7"
services:
  fpm:
    volumes:
      - 'ftp-get:/srv/pim/src/CoreBundle/Resources/E2OpenImport/work/'
      - 'ftp-put:/srv/pim/src/CISBundle/Resources/E2OpenCIS/'

  mysql:
    ports:
      - '3306:3306'

  mysql-backup:
    image: 'pcmt/mysql-backup:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '0 3 * * *'
      BACKUP_DIR: '/backup'
      PCMT_HOSTNAME: '${PCMT_HOSTNAME}'
    secrets:
      - mysql-creds
    volumes:
      - backup:/backup
    networks:
      - 'pim'

  asset-backup:
    image: 'pcmt/asset-backup:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '0 3 * * *'
      PCMT_HOSTNAME: '${PCMT_HOSTNAME}'
    volumes:
      - backup:/backup
      - file_storage:/pim-assets/file_storage
    networks:
      - 'pim'

  s3-sync:
    image: 'pcmt/s3:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '15 3 * * *'
      LOCAL_DIR_TO_SYNC_OUT: '/backup'
      S3_BUCKET: "${PCMT_S3_BUCKET}"
    volumes:
      - backup:/backup
    secrets:
      - s3-creds
      
  az-sync:
    image: 'pcmt/az-storage:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '15 3 * * *'
      LOCAL_DIR_TO_SYNC_OUT: '/backup'
      AZURE_STORAGE_ACCOUNT: "${PCMT_AZURE_STORAGE_ACCOUNT}"
      AZURE_STORAGE_CONTAINER_NAME: "${PCMT_AZURE_STORAGE_CONTAINER_NAME}"
    volumes:
      - backup:/backup
    secrets:
      - azure-creds

  ftp-get:
    image: 'pcmt/ftp-get:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '*/10 * * * *'
      SFTP_PRIVKEY_FILENAME: '/run/secrets/sftp-privkey'
      SFTP_LOCAL_DIR: '/srv/pim/src/CoreBundle/Resources/E2OpenImport/work/'
    volumes:
      - 'ftp-get:/srv/pim/src/CoreBundle/Resources/E2OpenImport/work/'
    secrets:
      - ftp-get-creds
      - sftp-privkey

  ftp-put:
    image: 'pcmt/ftp-put:${PCMT_VER:-3.0.0-snapshot}'
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '*/10 * * * *'
      SFTP_PRIVKEY_FILENAME: '/run/secrets/sftp-privkey'
      SFTP_LOCAL_DIR: '/uploads/work/'
      SFTP_LOCAL_ARCHIVE_DIR: '/uploads/done/'
    volumes:
      - 'ftp-put:/uploads'
    secrets:
      - ftp-put-creds
      - sftp-privkey

volumes:
  backup:
    driver: local
  ftp-get:
    driver: local
  ftp-put:
    driver: local
  file_storage:
    driver: local

secrets:
  mysql-creds:
    file: "${PCMT_MYSQL_CREDS_CONF:-./conf/mysql-creds.env}"
  s3-creds:
    file: "${PCMT_S3_CREDS_CONF:-./conf/aws-s3-creds.env.dist}"
  azure-creds:
    file: "${AZURE_CREDENTIALS_FILE:-./conf/azure-creds.env.dist}"
  ftp-get-creds:
    file: "${PCMT_FTP_GET_CREDS_CONF:-./conf/ftp-get-creds.env.dist}"
  ftp-put-creds:
    file: "${PCMT_FTP_PUT_CREDS_CONF:-./conf/ftp-put-creds.env.dist}"
  sftp-privkey:
    file: "${PCMT_SFTP_PRIVKEY_FILENAME:-./conf/sftp-privkey.dist}"
      