######################################################################
# Copyright (c) 2023, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: '3.7'
services:

  httpd:
    labels:
      - "traefik.http.routers.http.entrypoints=websecure"
      - "traefik.http.routers.http.tls.certresolver=myresolver"
      - "traefik.http.middlewares.http.redirectscheme.scheme=https"
      - "traefik.http.middlewares.http.redirectscheme.permanent=true"
      - "traefik.http.middlewares.http.redirectscheme.port=443"
  reverse-proxy:
    command:
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pcmt2@villagereach.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${DOCKER_PORT_HTTPS:-443}:443"
    volumes:
      - type: volume
        source: traefikdata
        target: "/letsencrypt"
  
volumes:
  traefikdata:
    driver: local