[program:akeneo_queue_daemon]
command=php bin/console messenger:consume ui_job import_export_job data_maintenance_job --env=prod -vv
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/akeneo_daemon.err.log
stdout_logfile=/var/log/supervisor/akeneo_daemon.out.log
user=www-data
stopasgroup=true